### ISSUE TITLE
Is it possible to repo sync w/out network?

### ISSUE THREAD

**Issue by lyance** [guillon/repo-mirror#3]
Hi.  I was able to create a mirror and repo sync successfully with your great tool.  I was wondering if it would be possible, once I'm able to create the mirrors while online, to go offline (network unplugged) and do a "repo sync" of the same repository.  That would be nice to have.

Thanks and great job BTW.

**Comment by guillon** [comment]
Thks for the feedback, indeed I find the tool very useful on day-to-day usage and very stable imho, actually transparent as I have it aliased to repo. Happy you enjoy it.

For the no-network use case, frankly it is not in the initial motivations for repo-mirror, hence I'm not sure I would be able to add this feature seamlessly.
Anyway, what is more precisely the use case? You expect that a no-network sync may fail due to missing local references in the mirror if it is not up-to-date? Would it be to have the possibility to easily create a new work dir on a already mirrored manifest? Do you know an equivalent use case with repo alone?

**Comment by lyance** [comment]
Thanks for replying.  Yes, for me the no-network use would allow me to create a new work dir on an already mirrored manifest.  Would be used in times when I'm away from the office network and had to suddenly create work dirs.  I work often with Yocto-based S/W trees and with Yocto, there's this BB_NO_NETWORK=1 flag that allows a build to run even without a network connection (assuming the download local cache is up-to-date).  Having repo-mirror support this will complete the setup of repo-sync'ing and building without a network connection.

I understand that this might complicate things and take effort/time.  No worries about it not being available right now.  As it is, I am still able to find repo-mirror very useful.
